<body style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 auto;padding: 0;min-width: 320px; max-width: 45rem;">
    <header style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;flex-wrap: wrap;align-content: center;justify-content: center;height: 4.375rem;font-family: 'Archivo';font-weight: 700;text-transform: uppercase;text-decoration: none;letter-spacing: 2.6px;color: #111111;box-shadow: 0px 3px 6px 0px rgba(139, 139, 139, 0.2509803922);">
        <h1 style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;align-self: center;order: 2;font-size: 0.8rem;width: 8.5rem;margin-left: 1rem;">Hotel <span style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;font-weight: 400;">Miranda</span></h1>
        <img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/header_logo.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;order: 1;width: 2.25rem;height: 2.25rem;box-shadow: 0px 14px 24px 0px rgba(139, 139, 139, 0.2509803922);">
    </header>

    <main style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;">
        <div class="main" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;">
            <div class="main__info" style="scroll-behavior: smooth;box-sizing: border-box;margin: 3rem 1.25rem;padding: 0;">
                <div class="main__info__text" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;">
                    <p style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;margin-block: 0.625rem;font-family: 'Old Standard TT';font-weight: 400;font-size: 2.5rem;line-height: 3rem;letter-spacing: -1.44px;color: #222222;">Your Booked Room</p>
                </div>
                <img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/hotel-room-3.jpg" alt="image of a room" class="main__info__image" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;width: 100%;">
            </div>
            <div class="main__receipt" style="scroll-behavior: smooth;box-sizing: border-box;margin: 1.25rem;padding: 0;">
                <h3 class="main__receipt__title" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;font-family: 'Old Standard TT';font-weight: 400;font-size: 1.875rem;line-height: 1.875rem;color: #222222;">Receipt</h3>
                <hr style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;width: 100%;margin-block: 1rem 1.5rem;border: 1px solid #F1F1F1;">
                <div class="main__receipt__content" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: grid;grid-template-columns: auto;column-gap: 1rem;row-gap: 1rem;margin-block: 2.8125rem 5.625rem;">
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Room type:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">Double Bed</h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Room floor:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">Floor 1, Room 4</h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Price:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">$345/night</h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Check in:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">22/05/2026</h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Check out:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">29/05/2026</h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Description:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">Phasellus volutpat neque a tellus venenatis, a
                        euismod augue facilisis. Fusce ut metus mattis, consequat metus nec, luctus lectus. Pellentesque
                        orci quis hendrerit sed eu dolor. Cancel up to 14 days to get a full refund.</h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Amenities:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">
                        <ul style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;list-style-type: none;">
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/ac.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Air Conditioner</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/wifi-amenities.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">High speed WiFi</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/breakfast.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Breakfast</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/kitchen.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Kitchen</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/cleaning.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Cleaning</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/shower.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Shower</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/groceries.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Grocery</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/bed-amenities.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Single bed</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/shop.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Shop near</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/towel.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Towels</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/support.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">24/7 Online Support</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/locker.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Strong Locker</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/security.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Smart Security</li>
                            <li style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;padding-bottom: 0.25rem;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/team.svg" alt="team icon" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0 0.25rem 0.25rem 0;padding: 0;width: 1rem;">Expert Team</li>
                        </ul>
                    </h5>
                    <h4 class="main__receipt__content__name" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 1;font-family: 'Roboto';font-weight: 700;font-size: 1rem;color: #222222;">Cancellation policy:</h4>
                    <h5 class="main__receipt__content__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;grid-column: 2;font-family: 'Roboto';font-weight: 400;font-size: 1rem;color: #777777;">Phasellus volutpat neque a tellus venenatis, a
                        euismod augue facilisis. Fusce ut metus mattis, consequat metus nec, luctus lectus. Pellentesque
                        orci quis hendrerit sed eu dolor. Cancel up to 14 days to get a full refund.</h5>
                </div>
            </div>
        </div>
    </main>

    <footer style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;background-image: url('http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/footer background.png');background-color: rgba(255, 255, 255, 0.98);background-blend-mode: lighten;">
        <div class="footer" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 1.25rem;display: flex;flex-direction: column;">
            <div class="footer__data" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;">
                <div class="footer__data__logo" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;margin-bottom: 3.125rem;font-family: 'Archivo';font-weight: 700;text-transform: uppercase;letter-spacing: 2.6px;color: #111111;">
                    <h1 style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;align-self: center;order: 2;font-size: 1.625rem;margin-left: 1.75rem;">Hotel <span style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;font-weight: 400;">Miranda</span></h1>
                    <img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/footer_logo.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;order: 1;width: 5rem;height: 5rem;box-shadow: 0px 14px 24px 0px rgba(139, 139, 139, 0.1490196078);">
                </div>
                <p class="footer__data__description" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;color: #777777;font-family: 'Archivo';font-weight: 400;font-size: 1rem;line-height: 1.625rem;margin-bottom: 2rem;">Thank you for trusting our services.</p>
                <div class="footer__data__social_media" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;display: flex;margin-bottom: 2rem;">
                    <a class="footer__data__social_media__link" href="https://www.facebook.com/" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;text-decoration: none;display: flex;flex-wrap: wrap;align-content: center;justify-content: center;width: 2.5rem;height: 2.5rem;margin-right: 0.625rem;background-color: #F8F8F8;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/facebook.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;"></a>
                    <a class="footer__data__social_media__link footer__data__social_media__link--twitter" href="https://www.twitter.com/" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;text-decoration: none;display: flex;flex-wrap: wrap;align-content: center;justify-content: center;width: 2.5rem;height: 2.5rem;margin-right: 0.625rem;background-color: #BEAD8E;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/Twitter.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;"></a>
                    <a class="footer__data__social_media__link" href="https://www.behance.net/" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;text-decoration: none;display: flex;flex-wrap: wrap;align-content: center;justify-content: center;width: 2.5rem;height: 2.5rem;margin-right: 0.625rem;background-color: #F8F8F8;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/Behance.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;"></a>
                    <a class="footer__data__social_media__link" href="https://es.linkedin.com/" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;text-decoration: none;display: flex;flex-wrap: wrap;align-content: center;justify-content: center;width: 2.5rem;height: 2.5rem;margin-right: 0.625rem;background-color: #F8F8F8;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/Linkedin.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;"></a>
                    <a class="footer__data__social_media__link" href="https://www.youtube.com/" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;text-decoration: none;display: flex;flex-wrap: wrap;align-content: center;justify-content: center;width: 2.5rem;height: 2.5rem;margin-right: 0.625rem;background-color: #F8F8F8;"><img src="http://ec2-35-180-116-78.eu-west-3.compute.amazonaws.com/img/Youtube.svg" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;"></a>
                </div>
            </div>
        </div>
        <div class="footer__legal" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0;background-color: #F8F8F8;width: 100%;padding-block: 0.4375rem;">
            <p class="footer__legal__text" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0.75rem 1.25rem;font-family: 'Roboto';font-weight: 700;font-size: 1rem;line-height: 100%;letter-spacing: -0.48px;color: #222222;">Copyright By@Example - 2020</p>
            <p class="footer__legal__text" style="scroll-behavior: smooth;box-sizing: border-box;margin: 0;padding: 0.75rem 1.25rem;font-family: 'Roboto';font-weight: 700;font-size: 1rem;line-height: 100%;letter-spacing: -0.48px;color: #222222;">Terms of use | Privacy Environmental Policy</p>
        </div>
    </footer>
</body>